# Generated by Django 6.0.5 on 2026-05-15 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('emergency_contact', models.CharField(max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('qr', models.ImageField(null=True, upload_to='qr/')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.familygroup')),
            ],
        ),
    ]
